import { NextRequest, NextResponse } from "next/server";
import type { GeneratedPortfolio } from "@/types/portfolio";

function uint16LE(n: number): number[] {
    return [n & 0xff, (n >> 8) & 0xff];
}
function uint32LE(n: number): number[] {
    return [n & 0xff, (n >> 8) & 0xff, (n >> 16) & 0xff, (n >> 24) & 0xff];
}

function crc32(bytes: number[]): number {
    const table: number[] = [];
    for (let i = 0; i < 256; i++) {
        let c = i;
        for (let j = 0; j < 8; j++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
        table[i] = c;
    }
    let crc = 0xffffffff;
    for (const b of bytes) crc = table[(crc ^ b) & 0xff] ^ (crc >>> 8);
    return (crc ^ 0xffffffff) >>> 0;
}

function strToBytes(s: string): number[] {
    const out: number[] = [];
    for (let i = 0; i < s.length; i++) {
        const code = s.charCodeAt(i);
        if (code < 128) {
            out.push(code);
        } else if (code < 2048) {
            out.push(0xc0 | (code >> 6), 0x80 | (code & 0x3f));
        } else {
            out.push(0xe0 | (code >> 12), 0x80 | ((code >> 6) & 0x3f), 0x80 | (code & 0x3f));
        }
    }
    return out;
}

function buildZip(files: Array<{ path: string; content: string }>): ArrayBuffer {
    const entries: Array<{
        pathBytes: number[];
        dataBytes: number[];
        crc: number;
        offset: number;
    }> = [];

    const localParts: number[] = [];
    let offset = 0;

    for (const f of files) {
        const pathBytes = strToBytes(f.path);
        const dataBytes = strToBytes(f.content);
        const crc = crc32(dataBytes);

        const localHeader = [
            0x50, 0x4b, 0x03, 0x04,
            20, 0,
            0, 0,
            0, 0,
            0, 0, 0, 0,
            ...uint32LE(crc),
            ...uint32LE(dataBytes.length),
            ...uint32LE(dataBytes.length),
            ...uint16LE(pathBytes.length),
            0, 0,
        ];

        entries.push({ pathBytes, dataBytes, crc, offset });
        offset += localHeader.length + pathBytes.length + dataBytes.length;

        for (const b of localHeader) localParts.push(b);
        for (const b of pathBytes) localParts.push(b);
        for (const b of dataBytes) localParts.push(b);
    }

    const cdParts: number[] = [];
    const cdStart = offset;

    for (const entry of entries) {
        const cdEntry = [
            0x50, 0x4b, 0x01, 0x02,
            20, 0,
            20, 0,
            0, 0,
            0, 0,
            0, 0, 0, 0,
            ...uint32LE(entry.crc),
            ...uint32LE(entry.dataBytes.length),
            ...uint32LE(entry.dataBytes.length),
            ...uint16LE(entry.pathBytes.length),
            0, 0,
            0, 0,
            0, 0,
            0, 0, 0, 0,
            ...uint32LE(entry.offset),
        ];
        for (const b of cdEntry) cdParts.push(b);
        for (const b of entry.pathBytes) cdParts.push(b);
    }

    const cdSize = cdParts.length;

    const eocd = [
        0x50, 0x4b, 0x05, 0x06,
        0, 0,
        0, 0,
        ...uint16LE(entries.length),
        ...uint16LE(entries.length),
        ...uint32LE(cdSize),
        ...uint32LE(cdStart),
        0, 0,
    ];

    const all = [...localParts, ...cdParts, ...eocd];
    const buf = new ArrayBuffer(all.length);
    const view = new Uint8Array(buf);
    for (let i = 0; i < all.length; i++) view[i] = all[i];
    return buf;
}

export async function POST(req: NextRequest) {
    try {
        const portfolio: GeneratedPortfolio = await req.json();

        if (!portfolio.files || !Array.isArray(portfolio.files)) {
            return NextResponse.json({ error: "Invalid portfolio data" }, { status: 400 });
        }

        const hasReadme = portfolio.files.some((f) => f.path.toLowerCase().includes("readme"));
        const files = hasReadme
            ? portfolio.files
            : [
                ...portfolio.files,
                {
                    path: "README.md",
                    content: `# My Portfolio\n\nGenerated by ResumeAI\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
                    language: "markdown",
                },
            ];

        const zipBuffer = buildZip(
            files.map((f) => ({ path: `portfolio/${f.path}`, content: f.content }))
        );

        return new NextResponse(zipBuffer, {
            headers: {
                "Content-Type": "application/zip",
                "Content-Disposition": "attachment; filename=portfolio.zip",
                "Content-Length": zipBuffer.byteLength.toString(),
            },
        });
    } catch (error) {
        console.error("[Portfolio Export]", error);
        return NextResponse.json({ error: "Export failed" }, { status: 500 });
    }
}
